const data=[
    {
        "name":"Action",
        "color":"#f44336"
    },
    {
        "name":"Adventure",
        "color":"#E91E63"
    },
    {
        "name":"Animation",
        "color":"#9C27B0"
    },
    {
        "name":"Biography",
        "color":"#673AB7"
    },
    {
        "name":"Comedy",
        "color":"#3F51B5"
    },
    {
        "name":"Crime",
        "color":"#2196F3"
    },   {
        "name":"Documentary",
        "color":"#00BCD4"
    },
    {
        "name":"Drama",
        "color":"#009688"
    },
    {
        "name":"Family",
        "color":"#4CAF50"
    },   {
        "name":"Fantasy",
        "color":"#8BC34A"
    },
    {
        "name":"Film Noir",
        "color":"#CDDC39"
    },
    {
        "name":"History",
        "color":"#FFEB3B"
    },
    {
        "name":"Horror",
        "color":"#FFC107"
    },
    {
        "name":"Music",
        "color":"#FF9800"
    },
    {
        "name":"Musical",
        "color":"#FF5722"
    },
    {
        "name":"Mystery",
        "color":"#795548"
    },
    {
        "name":"Romance",
        "color":"#9E9E9E"
    },
    {
        "name":"Sci-Fi",
        "color":"#607D8B"
    },
    {
        "name":"Short Film",
        "color":"#FF3D00"
    },
    {
        "name":"Sport",
        "color":"#FF9100"
    },
    {
        "name":"Superhero",
        "color":"#FFC400"
    },
    {
        "name":"Thriller",
        "color":"#00B0FF"
    },
    {
        "name":"War",
        "color":"#651FFF"
    },
    {
        "name":"Western",
        "color":"#F50057"
    },
    

];
export default data;
